version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bookshelf-db
    environment:
      POSTGRES_DB: bookshelf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bookshelf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Bookshelf API
  bookshelf-api:
    image: ${DOCKER_USERNAME}/bookshelf-api:latest
    container_name: bookshelf-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bookshelf
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "7070:7070"
    networks:
      - bookshelf-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Watchtower - Auto-update containers
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  bookshelf-network:
    driver: bridge
